---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: solver-fedora-30-py37
  annotations:
    thoth-station.ninja/template-version: 0.10.0-dev
  labels:
    app: thoth
    component: solver
spec:
  templates:
    - name: solve
      inputs:
        parameters:
          - name: THOTH_SOLVER_DOCUMENT_ID
          - name: THOTH_LOG_SOLVER
            value: "INFO"
          - name: THOTH_SOLVER_NO_TRANSITIVE
            value: "1"
          - name: THOTH_SOLVER_PACKAGES
          - name: THOTH_SOLVER_INDEXES
            value: "https://pypi.org/simple"
      outputs:
        artifacts:
          - name: solver-document
            path: /mnt/workdir
      container:
        name: solver
        image: solver-fedora-30-py37
        env:
          - name: THOTH_SOLVER
            value: solver-fedora-30-py37
          - name: THOTH_LOG_SOLVER
            value: "{{inputs.parameters.THOTH_LOG_SOLVER}}"
          - name: THOTH_SOLVER_NO_TRANSITIVE
            value: "{{inputs.parameters.THOTH_SOLVER_NO_TRANSITIVE}}"
          - name: THOTH_SOLVER_PACKAGES
            value: "{{inputs.parameters.THOTH_SOLVER_PACKAGES}}"
          - name: THOTH_SOLVER_OUTPUT
            value: "/mnt/workdir/{{inputs.parameters.THOTH_SOLVER_DOCUMENT_ID}}"
          - name: THOTH_SOLVER_INDEXES
            value: "{{inputs.parameters.THOTH_SOLVER_INDEXES}}"
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: thoth
                key: sentry-dsn
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                key: storage-bucket-name
                name: thoth
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workdir
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
