---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: solver-
  annotations:
    thoth-station.ninja/template-version: 0.10.0-dev
  labels:
    app: thoth
    component: solver
spec:
  serviceAccountName: argo
  entrypoint: solve-and-sync
  arguments:
    parameters:
      # should not have dots?! s3 problem?!
      - name: THOTH_SOLVER_DOCUMENT_ID
      - name: THOTH_LOG_SOLVER
        value: "INFO"
      - name: THOTH_SOLVER_NO_TRANSITIVE
        value: 1
      - name: THOTH_SOLVER_PACKAGES
      - name: THOTH_SOLVER_INDEXES
        value: "https://pypi.org/simple"
      - name: THOTH_FORCE_SYNC
        value: "0"
  volumes:
    - name: workdir
      emptyDir: {}
  templates:
    - name: solve-and-sync
      archiveLocation:
        archiveLogs: true
      dag:
        tasks:
          - name: solverhel80py36
            templateRef:
              name: solver-rhel-8.0-py36
              template: solve
            arguments:
              parameters:
                - name: THOTH_SOLVER_DOCUMENT_ID
                  value: "{{workflow.parameters.THOTH_SOLVER_DOCUMENT_ID}}"
                - name: THOTH_LOG_SOLVER
                  value: "{{workflow.parameters.THOTH_LOG_SOLVER}}"
                - name: THOTH_SOLVER_NO_TRANSITIVE
                  value: "{{workflow.parameters.THOTH_SOLVER_NO_TRANSITIVE}}"
                - name: THOTH_SOLVER_PACKAGES
                  value: "{{workflow.parameters.THOTH_SOLVER_PACKAGES}}"
                - name: THOTH_SOLVER_INDEXES
                  value: "{{workflow.parameters.THOTH_SOLVER_INDEXES}}"

          - name: graph-sync
            dependencies:
              - solverhel80py36
            templateRef:
              name: graph-sync
              template: solver
            arguments:
              artifacts:
                - name: solver-document
                  from: "{{tasks.solverhel80py36.outputs.artifacts.solver-document}}"
              parameters:
                - name: THOTH_SOLVER_DOCUMENT_ID
                  value: "{{workflow.parameters.THOTH_SOLVER_DOCUMENT_ID}}"
                - name: THOTH_FORCE_SYNC
                  value: "{{workflow.parameters.THOTH_FORCE_SYNC}}"

          - name: debug-dump-solver-document
            dependencies:
              - solverhel80py36
            template: dump-solver-document
            arguments:
              artifacts:
                - name: solver-document
                  from: "{{tasks.solverhel80py36.outputs.artifacts.solver-document}}"

    - name: dump-solver-document
      inputs:
        artifacts:
          - name: solver-document
            path: "/mnt/solver/document/{{workflow.parameters.THOTH_SOLVER_DOCUMENT_ID}}.json"
      container:
        image: "argoproj/argoexec:latest"
        command: [sh, -c]
        args:
          [
            "cat /mnt/solver/document/{{workflow.parameters.THOTH_SOLVER_DOCUMENT_ID}}.json",
          ]
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
status: {}
